# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.snappypdf::lang.controllers.pdfs.label

# Model Form Field configuration
form: $/waka/snappypdf/models/pdf/fields.yaml

# Model Class name
modelClass: Waka\SnappyPdf\Models\Pdf

# Default redirect location
defaultRedirect: waka/snappypdf/pdfs

# Create page
create:
    title: backend::lang.form.create_title
    redirect: waka/snappypdf/pdfs/update/:id
    redirectClose: waka/snappypdf/pdfs

# Update page
update:
    title: backend::lang.form.update_title
    redirect: waka/snappypdf/pdfs/update/:id
    redirectClose: waka/snappypdf/pdfs

# Preview page
preview:
    title: backend::lang.form.preview_title
